# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='arrange',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Branch'),
        ),
        migrations.AddField(
            model_name='arrange',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Doctor'),
        ),
    ]
