# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arrange',
            unique_together=set([('doctor', 'branch')]),
        ),
    ]
