# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171217_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrange',
            name='arrange',
        ),
    ]
