# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_arrange_arrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='fri',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrange',
            name='mon',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrange',
            name='sat',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrange',
            name='sun',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrange',
            name='thu',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrange',
            name='tue',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrange',
            name='wed',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天'), ('休息', '休息')], default='休息', max_length=10),
        ),
    ]
